export const SKILLS = [
    {
        id: 0, 
        skillName: "HTML",
        image: "./assets/images/icons/html5.png",
        description: 'Proficient',
        years: '1 Year',
    },
    {
        id: 1, 
        skillName: "CSS",
        image: "./assets/images/icons/css.png",
        description: 'Proficient',
        years: '1 Year',
    },
    {
        id: 2, 
        skillName: "JavaScript",
        image: "./assets/images/icons/javascript.png",
        description: 'Proficient',
        years: '1 Year',
    },
    {
        id: 3, 
        skillName: "React",
        image: "./assets/images/icons/react.png",
        description: 'Intermediate',
        years: '1 Year',
    },
    {
        id: 4, 
        skillName: "Bootstrap",
        image: "./assets/images/icons/bootstrap.png",
        description: 'Intermediate',
        years: '1 Year',
    },
    {
        id: 5, 
        skillName: "Python",
        image: "./assets/images/icons/python.png",
        description: 'Intermediate',
        years: '2 Years',
    },
    {
        id: 6, 
        skillName: "Nodejs",
        image: "./assets/images/icons/nodejs-white.svg",
        description: 'Beginner',
        years: '1 Year',
    },
    {
        id: 7, 
        skillName: "MongoDB",
        image: "./assets/images/icons/mon.webp",
        description: 'Beginner',
        years: '1 Year',
    },
    {
        id: 8, 
        skillName: "Express",
        image: "./assets/images/icons/express.png",
        description: 'Beginner',
        years: '1 Year',
    },
    {
        id: 9, 
        skillName: "Aseprite",
        image: "./assets/images/icons/aseprite.png",
        description: 'Proficient',
        years: '3 Years',
    },
    {
        id: 10, 
        skillName: "Adobe Photoshop",
        image: "./assets/images/icons/photoshop.png",
        description: 'Intermediate',
        years: '2 Years',
    },
    {
        id: 11, 
        skillName: "DaVinci Resolve 17",
        image: "./assets/images/icons/davinciresolve.png",
        description: 'Intermediate',
        years: '1 Year',
    },
    
]